// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable} bg-black`}>
//         {/* Navbar */}
//         <div>
//           <nav className="navbar navbar-expand-lg navbar-light bg-light">
//   <div className="container-fluid">
//     <a className="navbar-brand" href="/">Navbar</a>
//     <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
//       <span className="navbar-toggler-icon"></span>
//     </button>
//     <div className="collapse navbar-collapse" id="navbarSupportedContent">
//       <ul className="navbar-nav me-auto mb-2 mb-lg-0">
//         <li className="nav-item">
//           <Link className="nav-link active" aria-current="page" href="/">Home</Link>
//         </li>
//         <li className="nav-item">
//           <Link className="nav-link" href="/contact">Contact</Link>
//         </li>
//         <li className="nav-item">
//           <Link className="nav-link" href="/about">About</Link>
//         </li>
//         <li className="nav-item">
//           <Link className="nav-link" href="/services">Services</Link>
//         </li>
//         <li className="nav-item dropdown">
//           <Link className="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
//             Dropdown
//           </Link>
//           <ul className="dropdown-menu" aria-labelledby="navbarDropdown">
//             <li><Link className="dropdown-item" href="#">Action</Link></li>
//             <li><Link className="dropdown-item" href="#">Another action</Link></li>
//             <li><hr className="dropdown-divider"/></li>
//             <li><Link className="dropdown-item" href="#">Something else here</Link></li>
//           </ul>
//         </li>
//         <li className="nav-item">
//           <Link className="nav-link disabled" href="#" tabIndex={-1} aria-disabled="true">Disabled</Link>
//         </li>
//       </ul>
//       <form className="d-flex">
//         <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
//         <button className="btn btn-outline-success" type="submit">Search</button>
//       </form>
//     </div>
//   </div>
// </nav>
//         </div>
//         {/* SideBar */}
//         <button className="btn btn-primary ms-2 mt-3" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Enable body scrolling</button>

// <div className="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabIndex={-1} id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
//   <div className="offcanvas-header">
//     <h5 className="offcanvas-title" id="offcanvasScrollingLabel">Offcanvas with body scrolling</h5>
//     <button type="button" className="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
//   </div>
//   <div className="offcanvas-body">
//     <p>Try scrolling the rest of the page to see this option in action.</p>
//   </div>
// </div>
//         <div>

//         </div>
//         {children}
//         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App with Sidebar",
  description: "Next.js Bootstrap Sidebar Layout",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Bootstrap CSS */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} bg-light`}>

        {/* NavBar */}
        <nav className="navbar navbar-expand-lg navbar-dark bg-dark px-3">
          <button
            className="btn btn-outline-light me-3"
            data-bs-toggle="offcanvas"
            data-bs-target="#sidebar"
          >
            ☰
          </button>

          <Link className="navbar-brand" href="/">
            MyApp
          </Link>

          <div className="collapse navbar-collapse">
            <ul className="navbar-nav ms-auto">
              <li className="nav-item">
                <Link className="nav-link" href="/">Home</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" href="/about">About</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" href="/contact">Contact</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" href="/services">Services</Link>
              </li>
            </ul>
          </div>
        </nav>

       {/* SideBar */}
        <div
          className="offcanvas offcanvas-start"
          tabIndex={-1}
          id="sidebar"
        >
          <div className="offcanvas-header">
            <h5 className="offcanvas-title">Dashboard</h5>
            <button
              type="button"
              className="btn-close"
              data-bs-dismiss="offcanvas"
            ></button>
          </div>

          <div className="offcanvas-body">
            <ul className="list-group list-group-flush">
              <Link href="/" className="list-group-item list-group-item-action">
                Home
              </Link>
              <Link href="/services" className="list-group-item list-group-item-action">
               Services
              </Link>
              <Link href="/about" className="list-group-item list-group-item-action">
                 About
              </Link>
              <Link href="/contact" className="list-group-item list-group-item-action">
               Contact
              </Link>
            </ul>
          </div>
        </div>

        {/* Pages */}
        <main className="container mt-4">
          {children}
        </main>

        {/* Bootstrap Script */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}

